# This workflows will upload a Python Package using github action and Trusted publishing
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# Status: 
# - verified action triggered by the new release.
# - correct upload to with test.pypi
# - correct installation from test.pypi.org: pip install --index-url https://test.pypi.org/simple/ publish-test


name: Build & upload PyPI package

on:
  push:
    branches: [master]
    tags: ["*"]
  release:
    types:
      - published
  workflow_dispatch:


jobs:
  # Upload to Test PyPI on every commit on main.
  release-test-pypi:
    name: Publish in-dev package to test.pypi.org
    #environment: release-test-pypi
    #if: github.repository_owner == 'python-attrs' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-package

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build
        run: |
          python setup.py sdist bdist_wheel
          ls -l dist
          
      - name: Upload package to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true  
          repository-url: https://test.pypi.org/legacy/
          # No authentication, Trusted Publisher Management via. OpenID Connect (OIDC) shuould be used 


  # Upload to real PyPI on GitHub Releases.
  # release-pypi:
  #   name: Publish released package to pypi.org
  #   environment: release-pypi
  #   if: github.repository_owner == 'python-attrs' && github.event.action == 'published'
  #   runs-on: ubuntu-latest
  #   needs: build-package
  # 
  #   permissions:
  #     id-token: write
  # 
  #   steps:
  #     - name: Download packages built by build-and-inspect-python-package
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: Packages
  #         path: dist
  # 
  #     - name: Upload package to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         attestations: true
